### ISSUE TITLE
Missing response headers.

### ISSUE THREAD

**Issue by jose-acevedoflores** [wascc/http-server-provider#9]
I've been playing around with the server provider and noticed the headers were not propagated from the codec::http::Response struct onto the actix_web::HttpReponse. 

I modified the `Ok` branch of the `match` block inside the `request_handler` function to propagate the headers 
like this to fix my issue:
```diff
    Ok(r) => {
             let r = deserialize::<codec::http::Response>(r.as_slice()).unwrap();
-            HttpResponse::with_body(
+            let mut response = HttpResponse::with_body(
                 StatusCode::from_u16(r.status_code as _).unwrap(),
                 Body::from_slice(&r.body),
-            )
+            );
+            if !r.header.is_empty() {
+                let headers = response.head_mut();
+                r.header.iter().for_each(|(key, val)| {
+                    headers.headers.insert(HeaderName::from_bytes(key.as_bytes()).unwrap(),
+                                           HeaderValue::from_str(val).unwrap());
+                });
+            }
+
+            response

```

I'm fairly new to rust and trying to get some exposure to it so my fix might need some work.
I'd be happy to submit a Pull Request with those changes if they are ok.

**Comment by autodidaddict** [comment]
@jose-acevedoflores I would love it if you could submit this as a pull request. Thanks so much for contributing!
